In [1]:
import numpy as np

In [2]:
np.array([10,20,24,5,15,50])

array([10, 20, 24,  5, 15, 50])

In [4]:
a = np.array([10, 30, 20, 4, 30, 51, 7, 2, 4, 40, 100])
a[4]

30

In [5]:
a[3:] #Apartir de ese indice en adelante nos muestre la información

array([  4,  30,  51,   7,   2,   4,  40, 100])

In [6]:
a[3:7]

array([ 4, 30, 51,  7])

In [7]:
a[1::4] #Cada cuantas posiciones quiero que imprima en este caso cada cuatro elementos

array([30, 51, 40])

In [8]:
np.zeros(5) #El numero es el parametro, en este caso la cantidad de elementos que contiene el arreglo

array([0., 0., 0., 0., 0.])

In [9]:
np.ones((4,5)) #creación de dos parametros por eso va en parentesis dobles 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
type(np.ones(())) #Para saber de que tipo de arreglo es

numpy.ndarray

In [16]:
type(np.ones(([3])))

numpy.ndarray

In [17]:
np.linspace(3, 10, 5) #Primer parametro es numero inferior de donde parte, el segundo es el numero maximo 
                      #El ultimo es el numero de elementos que contiene

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [20]:
b = np.array([['X', 'y', 'z'], ['a', 'c', 'e']])
print(b)
type(b)

[['X' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [21]:
b.ndim #Para saber las dimesiones que tiene el arreglo

2

In [23]:
c =[12, 4, 10, 40, 2]
np.sort(c) #Ordena el arreglo de menor a mayor

array([ 2,  4, 10, 12, 40])

In [27]:
cabeceras = [('nombre','S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15)]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

In [28]:
#Llena de manera dinamica
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
np.arange(5,30) #Limite inferior y superior

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
np.arange(5, 50, 5) #Primer valor de donde inicia, segundo valor hasta donde va y tercer valor el incremento

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [31]:
np.full((3,5),10)
#Primer parentesis contiene los tamaños de la matriz y el valor por fuera indica el numero con el cual sera llenao

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [32]:
np.diag([0, 3, 9, 20])
#Indicas que quieres una diagonal con esos valores en un arreglo bidimensional

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 20]])